### ISSUE TITLE
every solution in the runtest example is exactly the same

### ISSUE THREAD

**Issue by jamesjscully** [JuliaDiffEq/DiffEqGPU.jl#14]
Using the lorenz setup in the runtest file I noticed that all of the solutions are the same. 
``
sol = solve(monteprob,Tsit5(),EnsembleGPUArray(),trajectories=100_000,saveat=1.0f0)
filter(x -> x.u != sol.u[1].u, sol.u) # 0 element array
``

**Comment by nilsbecker** [comment]
this looks similar to #13

**Comment by ChrisRackauckas** [comment]
Are you running the older version of the tests? https://github.com/JuliaDiffEq/DiffEqGPU.jl/blob/v0.1.0/test/runtests.jl that would do it. Test this on master since this repo is still growing fast. If master tests aren't working for you, let's continue this, but I'm closing since I believe this is probably just running the wrong test file.

**Comment by jamesjscully** [comment]
yep, works on master
